describe('Pruebas de cypress', () => {
    it("Validar iniciar sesion y cerrar sesion", () => {
        cy.visit("https://the-internet.herokuapp.com/login")
        cy.get('[name="username"]').type('tomsmith')
        cy.get('[name="password"]').type('SuperSecretPassword!')
        cy.get('#login').submit()
        cy.url().should('eq', 'https://the-internet.herokuapp.com/secure')
        cy.get('#flash').should('contain', 'You logged into a secure area!')
        cy.get('.button').click()
        cy.url().should('eq', 'https://the-internet.herokuapp.com/login')
    })
    it("validar login con credenciales incorrectas", () => {
        cy.visit("https://the-internet.herokuapp.com/login")
        cy.get('[name="username"]').type('usuario1')
        cy.get('[name="password"]').type('Password!')
        cy.get('#login').submit()
        cy.url().should('eq', 'https://the-internet.herokuapp.com/login')
        cy.get('#flash').should('contain','Your username is invalid!')
    })
})